AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 180
    MemorySize: 10000
  Api:
    BinaryMediaTypes:
      - image/png
      - image/jpg
      - image/jpeg

Resources:
  InterquAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage

  VideoUploadStatemachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/InterviewVideoUpload.asl.json
      DefinitionSubstitutions:
        SplitVideoFunctionArn: !GetAtt SplitVideoFunction.Arn
        GetExpressionFunctionArn: !GetAtt ExpressionInferenceFunction.Arn
        GetSentimentFunctionArn: !GetAtt AudioSentimentInferenceFunction.Arn
        GPTAnalysisFunctionArn: !GetAtt GPTAnalysisFunction.Arn
        PublishMongoFunctionArn : !GetAtt PublishMongoFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref SplitVideoFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ExpressionInferenceFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AudioSentimentInferenceFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref GPTAnalysisFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PublishMongoFunction

  AudioSentimentInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        # - arm64
        - x86_64
      ReservedConcurrentExecutions: 1
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref InterquAPI
            Path: /get_sentiment
            Method: get
            Auth:
              ApiKeyRequired: true
      Policies: 
      Environment:
        Variables: # Environment variables
          NUMBA_CACHE_DIR: /tmp/
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/get_sentiment
      DockerTag: python3.9-v1

  ExpressionInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ReservedConcurrentExecutions: 1
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref InterquAPI
            Path: /get_expression
            Method: get
            Auth:
              ApiKeyRequired: true
      Policies: AmazonS3ReadOnlyAccess
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/get_expression
      DockerTag: python3.10-v1

  # VideoProcessFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: functions/process_video/
  #     Handler: app.lambda_handler
  #     Runtime: python3.9
  #     Architectures:
  #       - x86_64
  #     Events:
  #       ProcessVideo:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           RestApiId: !Ref InterquAPI
  #           Path: /process_video
  #           Method: get
  #           Auth:
  #             ApiKeyRequired: true

  SplitVideoFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ReservedConcurrentExecutions: 1
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref InterquAPI
            Path: /get_expression
            Method: get
            Auth:
              ApiKeyRequired: true

      Policies: AmazonS3FullAccess
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./functions/split_video
      DockerTag: python3.10-v1
      
  AudioTranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_transcript/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        getTranscript:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref InterquAPI
            Path: /transcript
            Method: get
            Auth:
              ApiKeyRequired: true

  # WhisperFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: functions/get_whisper/
  #     Handler: app.lambda_handler
  #     Runtime: python3.9
  #     Architectures:
  #       - x86_64
  #     Events:
  #       getTranscript:
  #         Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  #         Properties:
  #           RestApiId: !Ref InterquAPI
  #           Path: /whisper
  #           Method: get
  #           Auth:
  #             ApiKeyRequired: true


  PublishMongoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/publishDB/
      Handler: MongoService.lambda_handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          MONGODB_URL: '{{resolve:ssm:/interqu/mongodb_url:1}}'

  GPTAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/gpt/
      Handler: ChatGPTService.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          OPENAI_API_KEY: '{{resolve:ssm:/interqu/openai_api_key:1}}'
      Architectures:
        - x86_64

  # Python layers
  FfmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/ffmpeg/
      CompatibleRuntimes:
        - python3.9
    # Metadata:
    #   BuildMethod: python3.9


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AudioSentimentInferenceFunction:
    Description: "API Gateway endpoint URL for Prod stage for Inference function"
    Value: !Sub "https://${InterquAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_sentiment/"
  InferenceFunction:
    Description: "Inference Lambda Function ARN"
    Value: !GetAtt AudioSentimentInferenceFunction.Arn
  InferenceFunctionIamRole:
    Description: "Implicit IAM Role created for Inference function"
    Value: !GetAtt AudioSentimentInferenceFunction.Arn
