AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Default: dev
  

Globals:
  Function:
    Timeout: 29
    MemorySize: 1024 
  Api:
    BinaryMediaTypes:
      - image/png
      - image/jpg
      - image/jpeg

Resources:
  InterquAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
        
  AudioSentimentInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        # - arm64
        - x86_64
      ReservedConcurrentExecutions: 1
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref InterquAPI
            Path: /get_sentiment
            Method: get
            Auth:
              ApiKeyRequired: true
      Policies: AmazonS3ReadOnlyAccess
      Environment:
        Variables: # Environment variables
          NUMBA_CACHE_DIR: /tmp/
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./get_sentiment
      DockerTag: python3.9-v1
        
  ExpressionInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ReservedConcurrentExecutions: 1
      Events:
        Inference:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref InterquAPI
            Path: /get_expression
            Method: get
            Auth:
              ApiKeyRequired: true
      Policies: AmazonS3ReadOnlyAccess
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./get_expression
      DockerTag: python3.10-v1


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AudioSentimentInferenceFunction:
    Description: "API Gateway endpoint URL for Prod stage for Inference function"
    Value: !Sub "https://${InterquAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_sentiment/"
  InferenceFunction:
    Description: "Inference Lambda Function ARN"
    Value: !GetAtt AudioSentimentInferenceFunction.Arn
  InferenceFunctionIamRole:
    Description: "Implicit IAM Role created for Inference function"
    Value: !GetAtt AudioSentimentInferenceFunction.Arn
